top_100/config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :songs

  root 'songs#index'

end

top_100/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

top_100/app/models/song.rb
class Song < ApplicationRecord
    validates_presence_of :title 
    validates_presence_of :artist
end

top_100/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

top_100/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all.order(:rank)
  end

  def show
  end

  def new
    @songs = Song.new
  end

  def create
    song = Song.new(song_params)

    if song.save
      redirect_to songs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(
      :title,
      :artist,
      :rank,
      :genre
    )
  end
end

top_100/app/helpers/application_helper.rb
module ApplicationHelper
end

top_100/app/helpers/songs_helper.rb
module SongsHelper
end

top_100/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono" rel="stylesheet">
    <title>Top100</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

top_100/app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= form_for @song do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
  
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  
    <%= f.label :rank %>
    <%= f.text_area :rank %>
  
    <%= f.label :genre %>
    <%= f.text_area :genre %>

  <%= f.submit class: 'waves-effect waves-light btn'%>
<% end %>

top_100/app/views/songs/index.html.erb
<div class="container">

<h1 class="center-align">Top 100 Songs!</h1>

<%= link_to 'New Song', new_song_path %>

    <ul>
        <% @songs.each do |song| %>
            <li>
            <%= link_to  song.title, song_path(song) %> - <%= song.artist %> - <%= song.rank %>
            </li>
        <% end %>
    </ul>
</div>

top_100/app/views/songs/new.html.erb
<h1>New Song</h1>
<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.label :rank %>
  <%= f.text_area :rank %>

  <%= f.label :genre %>
  <%= f.text_area :genre %>

  <%= f.submit class: 'waves-effect waves-light btn'%>
<% end %>

top_100/app/views/songs/show.html.erb
<div class="col s5">
    <div class="card small blue-grey darken-1">
        <div class="card-content white-text">
            <h4 class="card-title">Song Title: <%= @song.title %></h4>
                <h6>Artist: <%= @song.artist %></h6>

                <p>Genre: <%= @song.genre %></p>

                <p>Rank: <%= @song.rank %></p>


            <div class="card-action">
                <%= link_to 'Back to Song List', songs_path %>
                <%= link_to 'Edit song', edit_song_path(@song) %>
                <%= link_to 'Delete song', song_path(@song), method: :delete %>
            </div>
        </div>
    </div>
</div>